config/routes.rb
Rails.application.routes.draw do
  match 'results', :to                                      => 'results#index', :as   => 'results', :via           => :get
  match 'results/:survey_code', :to                         => 'results#show', :as    => 'result', :via            => :get
  match 'surveys', :to                                      => 'surveyor#new', :as    => 'available_surveys', :via => :get
  match 'surveys/:survey_code', :to                         => 'surveyor#create', :as => 'take_survey', :via       => :post
  match 'surveys/:survey_code/:response_set_code', :to      => 'surveyor#show', :as   => 'view_my_survey', :via    => :get
  match 'surveys/:survey_code/:response_set_code/take', :to => 'surveyor#edit', :as   => 'edit_my_survey', :via    => :get
  match 'surveys/:survey_code/:response_set_code', :to      => 'surveyor#update', :as => 'update_my_survey', :via  => :put
end                                                                                      

app/models/answer.rb
class Answer < ActiveRecord::Base
  unloadable
  include Surveyor::Models::AnswerMethods
end

app/models/dependency.rb
class Dependency < ActiveRecord::Base
  unloadable
  include Surveyor::Models::DependencyMethods
end

app/models/dependency_condition.rb
class DependencyCondition < ActiveRecord::Base
  unloadable
  include Surveyor::Models::DependencyConditionMethods
end

app/models/question.rb
class Question < ActiveRecord::Base
  unloadable
  include Surveyor::Models::QuestionMethods
end

app/models/question_group.rb
class QuestionGroup < ActiveRecord::Base
  unloadable
  include Surveyor::Models::QuestionGroupMethods
  
end

app/models/response.rb
class Response < ActiveRecord::Base
  unloadable
  include ActionView::Helpers::SanitizeHelper
  include Surveyor::Models::ResponseMethods

  validates_uniqueness_of :answer_id, :scope => [:question_id, :response_set_id]
 
end

app/models/response_set.rb
class ResponseSet < ActiveRecord::Base
  unloadable
  include Surveyor::Models::ResponseSetMethods

  def self.toggle_debug
    $DEBUG = !$DEBUG
  end
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  unloadable
  include Surveyor::Models::SurveyMethods  
end

app/models/survey_section.rb
class SurveySection < ActiveRecord::Base
  unloadable
  include Surveyor::Models::SurveySectionMethods
end

app/models/survey_section_sweeper.rb
class SurveySectionSweeper < ActionController::Caching::Sweeper
  observe :survey_section
  
  def after_save(section)
    expire_cache(section)
  end
  
  def after_destroy(section)
    expire_cache(section)
  end
  
  def expire_cache(section)
    expire_fregment "section_#{section.id}"
  end
end

app/models/validation.rb
class Validation < ActiveRecord::Base
  unloadable
  include Surveyor::Models::ValidationMethods
end

app/models/validation_condition.rb
class ValidationCondition < ActiveRecord::Base
  unloadable
  include Surveyor::Models::ValidationConditionMethods
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  helper 'surveyor'
  layout 'results' 
  def index
    @surveys = Survey.all
  end

  def show
    @survey = Survey.find_by_access_code(params[:survey_code])
    @response_sets = @survey.response_sets
    @questions = @survey.sections_with_questions.map(&:questions).flatten
  end
end

app/controllers/surveyor_controller.rb
require 'surveyor'
# Surveyor Controller allows a user to take a survey. It is semi-RESTful since it does not have a concrete representation model.
# The "resource" is a survey attempt/session populating a response set.
class SurveyorController < ApplicationController
  unloadable
  include Surveyor::SurveyorControllerMethods
  @@DEBUG = false
  def self.toggle_debug
    @@DEBUG = !@@DEBUG
  end
  def self.debug?
    @@DEBUG
  end
end

app/helpers/results_helper.rb
module ResultsHelper
  def display_response(r_set,question)
    sets = r_set.responses.select{|r| r.question.display_order == question.display_order}
	  	if sets.size == 0
  			return "-"
  		elsif sets.size == 1
  			return (sets.first.string_value || sets.first.text_value || show_answer(sets.first))
  		else
  		  txt = ""
        sets.each do |set|
          txt << show_answer(set) + "<br/>"
        end
        return txt
		  end
  end
  
  def show_answer(set)
     set.answer.text
  end
end

app/helpers/surveyor_helper.rb
module SurveyorHelper
  # Layout: stylsheets and javascripts
  def surveyor_includes
    surveyor_stylsheets + surveyor_javascripts    
  end
  def surveyor_stylsheets
    stylesheet_link_tag 'surveyor/reset', 'surveyor/dateinput', 'surveyor'
  end
  def surveyor_javascripts
    javascript_include_tag 'jquery','jquery-ui-1.8.9.custom.min', 'surveyor/jquery.surveyor'
  end
  # Helper for displaying warning/notice/error flash messages
  def flash_messages(types)
    types.map{|type| content_tag(:div, "#{flash[type]}".html_safe, :class => type.to_s)}.join.html_safe
  end
  # Section: dependencies, menu, previous and next
  def dependency_explanation_helper(question,response_set)
    # Attempts to explain why this dependent question needs to be answered by referenced the dependent question and users response
    trigger_responses = []
    dependent_questions = Question.find_all_by_id(question.dependency.dependency_conditions.map(&:question_id)).uniq
    response_set.responses.find_all_by_question_id(dependent_questions.map(&:id)).uniq.each do |resp|
      trigger_responses << resp.to_s
    end
    "&nbsp;&nbsp;You answered &quot;#{trigger_responses.join("&quot; and &quot;")}&quot; to the question &quot;#{dependent_questions.map(&:text).join("&quot;,&quot;")}&quot;".html_safe
  end
  def menu_button_for(section)
    submit_tag(section.title, :name => "section[#{section.id}]")
  end
  def previous_section
    # submit_tag("#{t ('surveyor.previous_section')} &raquo;", :name => "section[#{@section.previous.id}]") unless @section.previous.nil?
    # refactored to use copy in memory instead of making extra db calls
    submit_tag(t('surveyor.previous_section').html_safe, :name => "section[#{@sections[@sections.index(@section)-1].id}]") unless @sections.first == @section
  end
  def next_section
    # use copy in memory instead of making extra db calls
#    @sections.last == @section ? submit_tag(t('surveyor.click_here_to_finish'), :name => "finish") : submit_tag(t('surveyor.next_section'), :name => "section[#{@sections[@sections.index(@section)+1].id}]")
    @sections.last == @section ? submit_tag( "Finish", :name => "finish") : submit_tag(t('surveyor.next_section').html_safe,  :name => "section[#{@sections[@sections.index(@section)+1].id}]") 
  end
  
  # Questions
  def q_text(obj)
    @n ||= 0
    return image_tag(obj.text) if obj.is_a?(Question) and obj.display_type == "image"
    return obj.text if obj.is_a?(Question) and (obj.dependent? or obj.display_type == "label" or obj.part_of_group?)
    "#{@n += 1}) #{obj.text}"
  end
  # def split_text(text = "") # Split text into with "|" delimiter - parts to go before/after input element
  #   {:prefix => text.split("|")[0].blank? ? "&nbsp;" : text.split("|")[0], :postfix => text.split("|")[1] || "&nbsp;"}
  # end
  # def question_help_helper(question)
  #   question.help_text.blank? ? "" : %Q(<span class="question-help">#{question.help_text}</span>)
  # end
  
  # Answers
  def rc_to_attr(type_sym)
    case type_sym.to_s
    when /^date|time$/ then :datetime_value
    when /(string|text|integer|float|datetime)/ then "#{type_sym.to_s}_value".to_sym
    else :answer_id
    end
  end
  def rc_to_as(type_sym)
    case type_sym.to_s
    when /(integer|float)/ then :string
    else type_sym
    end
  end
  
  # Responses
  def response_for(response_set, question, answer = nil, response_group = nil)
    return nil unless response_set && question && question.id
    result = response_set.responses.detect{|r| (r.question_id == question.id) && (answer.blank? ? true : r.answer_id == answer.id) && (r.response_group.blank? ? true : r.response_group.to_i == response_group.to_i)}
    result.blank? ? response_set.responses.build(:question_id => question.id, :response_group => response_group) : result
  end
  def response_idx(increment = true)
    @rc ||= 0
    (increment ? @rc += 1 : @rc).to_s
  end  
end

app/views/layouts/results.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Survey: Result Sets</title>
  <%= surveyor_includes %>
</head>
<body>
  <div id="flash"><%= flash[:notice] %></div>
  <%= yield %>
</body>
</html>

app/views/layouts/surveyor_default.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Survey: <%= controller.action_name %></title>
  <%= surveyor_includes %>
</head>
<body>
  <div id="flash"><%= flash[:notice] %></div>
  <%= yield %>
</body>
</html>

app/views/partials/_answer.html.haml
-# TODO: disabled
- rg ||= nil
- r = response_for(@response_set, q, a, rg)
- i = response_idx(q.pick != "one") # argument will be false (don't increment i) if we're on radio buttons
= f.semantic_fields_for i, r do |ff|
  = ff.quiet_input :question_id unless q.pick == "one" # don't repeat question_id if we're on radio buttons
  = ff.quiet_input :id unless q.pick == "one" or r.new_record?
  = ff.quiet_input :response_group, :value => rg if q.pick != "one" && g && g.display_type == "repeater"
  
  - case q.pick
  - when "one"
    = ff.input :answer_id, :as => :surveyor_radio, :collection => [[a.text, a.id]], :label => false, :input_html => {:class => a.css_class}, :response_class => a.response_class
  - when "any"
    = ff.input :answer_id, :as => :surveyor_check_boxes, :collection => [[a.text, a.id]], :label => false, :input_html => {:class => a.css_class}, :response_class => a.response_class
  - when "none"
    - if %w(date datetime time float integer string text).include? a.response_class
      = ff.quiet_input :answer_id, :input_html => {:class => a.css_class, :value => a.id}
      - if r.value
        = ff.input rc_to_attr(a.response_class), :as => rc_to_as(a.response_class), :label => a.split_or_hidden_text(:pre).blank? ? false : a.split_or_hidden_text(:pre), :hint => a.split_or_hidden_text(:post)
      - else
        = ff.input rc_to_attr(a.response_class), :as => rc_to_as(a.response_class), :label => a.split_or_hidden_text(:pre).blank? ? false : a.split_or_hidden_text(:pre), :hint => a.split_or_hidden_text(:post), :input_html => {:value => a.default_value}
    - else
      = a.text

app/views/partials/_dependents.html.haml
#dependents
  .title Follow-up questions from your answers on the previous page
  -# @dependents.each_with_index do |question, index|
    = dependency_explanation_helper(question, @response_set)
    = render question.custom_renderer || "/partials/question", :question => question, :response_set => @response_set, :number => "D#{index+1}"

app/views/partials/_question.html.haml
-# TODO: js for slider
- rg ||= nil
- renderer = q.renderer(g ||= nil)
- f.inputs q_text(q), :id =>  "q_#{q.id}#{rg.nil? ? "" : "_" + rg}", :class => "q_#{renderer} #{renderer} #{q.css_class(@response_set)}" do
  %span.help= q.help_text
  - case renderer
  - when :image, :label
  - when :dropdown, :inline_dropdown, :slider
    - r = response_for(@response_set, q, nil, rg)
    - i = response_idx
    = f.semantic_fields_for i, r do |ff|
      = ff.quiet_input :question_id
      = ff.quiet_input :response_group, :value => rg if g && g.display_type == "repeater"
      = ff.input :answer_id, :as => :select, :collection => q.answers.map{|a| [a.text, a.id]}, :label => false
  - else # :default, :inline, :inline_default
    - if q.pick == "one"
      - r = response_for(@response_set, q, nil, rg)
      - i = response_idx  # increment the response index since the answer partial skips for q.pick == one
      = f.semantic_fields_for i, r do |ff|
        = ff.quiet_input :question_id
        = ff.quiet_input :response_group, :value => rg if g && g.display_type == "repeater"
        = ff.quiet_input :id unless r.new_record?
    - q.answers.each do |a|
      = render a.custom_renderer || '/partials/answer', :q => q, :a => a, :f => f, :rg => rg, :g => g

app/views/partials/_question_group.html.haml
- renderer = g.renderer
= f.inputs q_text(g), :id => "g_#{g.id}", :class => "g_#{renderer} #{g.css_class(@response_set)}" do
  %li.help= g.help_text
  - case renderer
    - when :grid
      %li
        %table
          %tbody
            - qs.each_slice(10) do |ten_questions| # header row every 10
              %tr
                %th &nbsp;
                - ten_questions.first.answers.each do |a|
                  %th= a.text
                %th &nbsp;
              - ten_questions.each_with_index do |q, i|
                %tr{:id => "q_#{q.id}", :class => "q_#{renderer} #{q.css_class(@response_set)}"}
                  %th= q.split_text(:pre)
                  - response_idx if q.pick == "one" # increment the response index since the answer partial skips for q.pick == one
                  - q.answers.each do |a|
                    %td= render a.custom_renderer || '/partials/answer', :g => g, :q => q, :a => a, :f => f
                  %th= q.split_text(:post)
    - when :repeater
      - (@response_set.count_group_responses(qs) + 1).times do |rg|
        %li
          - qs.each do |q|
            = render q.custom_renderer || "/partials/question", :g => g, :rg => rg, :q => q, :f => f
      = submit_tag("+ add row", :name => "section[#{@section.id}][g_#{g.id}]", :class => "add_row")
    - else # :inline
      - qs.each do |q|
        = render q.custom_renderer || "/partials/question", :g => g, :q => q, :f => f

app/views/partials/_section.html.haml
= div_for @section, :class => @section.custom_class do
  %span.title= @section.title
  - qs ||= []
  - (questions = @section.questions).each_with_index do |q, i|
    - if q.part_of_group?
      - qs << q # gather up the group questions
      - if (i+1 >= questions.size) or (q.question_group_id != questions[i+1].question_group_id)
        - # this is the last question of the section, or the group
        = render q.question_group.custom_renderer || "/partials/question_group", :g => q.question_group, :qs => qs, :f => f
        - qs = []
    - else # gather up the group questions
      = render q.custom_renderer || "/partials/question", :q => q, :f => f

app/views/partials/_section_menu.html.haml
.surveyor_menu
  %span.title= t('surveyor.sections')
  %ul
    - @sections.each do |s|
      %li{:class => ("active" if s == @section)}= menu_button_for(s)

app/views/results/index.html.erb
<h1>Listing Surveys</h1>

<table class="list_table">
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Operation</th>
  </tr>

<% @surveys.each do |survey| -%>
  <tr>
    <td><%=h survey.id %></td>
    <td><%=h survey.title %></td>
    <td><%= link_to "show results list(#{survey.response_sets.count})", result_path(survey.access_code) %></td>
  </tr>
<% end %>
</table>

app/views/results/show.html.erb
<table class="list_table">
  <tr>
    <th>ID</th>
    <th>Code</th>
	<% @questions.each do |question| %>
		<% next if question.display_order == 1 %>
		<th><%= "[" +question.display_order.to_s + "]" + question.text  %></th>
	<% end %>
  </tr>

<% @response_sets.each do |r_set| %>
  <tr>
    <td><%=h r_set.id %></td>
    <td><%=h r_set.access_code %></td>
	<% @questions.each do |question| %>
		<% next if question.display_order == 1 %>
		<td><%= display_response(r_set,question) %></td>
	<% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to "Back", results_path %>

app/views/surveyor/edit.html.haml
#surveyor
  %input#surveyor-title{:type=>"hidden", :value=>@survey.title}
  %input#surveyor-code{:type=>"hidden", :value=>@survey.access_code}
  %input#surveyor-response-code{:type=>"hidden", :value=>@response_set.access_code}
  %input#surveyor-current-section{:type=>"hidden", :value=>@section.id}
  - unless (types = flash.keys.select{|k| [:notice, :error, :warning].include?(k)}).blank?
    .surveyor_flash
      = flash_messages(types)
      .close
  - semantic_form_for(:r, @response_set, :url => update_my_survey_path, :html => {:method => :put, :id => "survey_form", :class => @survey.custom_class}) do |f|
    = render 'partials/section_menu' unless @sections.size < 3
    .survey_title= @survey.title
    .previous_section= previous_section
    = render 'partials/dependents' unless @dependents.empty?
    - if @response_set.no_responses_for_section?(@section) # cache if response_set has no responses for current section
      = render "/partials/section", :f => f
      /= cache("section_#{@section.id}"){ render "/partials/section", :f => f }
    - else # no cache
      = render "/partials/section", :f => f
    .next_section= next_section
  %br

app/views/surveyor/new.html.haml
#surveyor
  - unless (types = flash.keys.select{|k| [:notice, :error, :warning].include?(k)}).blank?
    .surveyor_flash
      = flash_messages(types)
      .close
  .survey_title= t('surveyor.take_these_surveys')
  %br
  #survey_list_wrap
    %ul#survey_list
      - unless @surveys.empty?
        - @surveys.each do |survey|
          %li.article
            %h5
              = survey.title
            .description
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vitae justo sit amet quam tempor dignissim. Sed eget diam id.
            .rating
              %span.popular Rating : Popular
            .recent-result.good
              recent result : good
            %ul.action
              %li
                - form_tag(take_survey_path(:survey_code => survey.access_code)) do 
                  %input.button.safe.normal.regular.questionnaire{:name=>"commit",:type=>"submit",:value=>"Questionnaire"} 
                  / = submit_tag( t('surveyor.take_it') )
              %li
                %a.button.normal.short{:href=>"#"} View Report
      - else
        %li
          No surveys

app/views/surveyor/show.html.haml
#surveyor
  - @survey.sections.each do |section|
    - div_for section do
      .title= section.title
      .questions
        - group_questions ||= []
        - section.questions.each_with_index do |question, index|
          - if question.part_of_group?
            - group_questions << question
            - if (index + 1 >= section.questions.size) or (question.question_group_id != section.questions[index + 1].question_group_id)
              - # skip to the last question of the section, or the last question of the group
              = render(:partial => "/partials/question_group", :locals => {:question_group => question.question_group, :response_set => @response_set, :group_questions => group_questions})
              - group_questions = []
          - else
            = render(:partial => "/partials/question", :locals => {:question => question, :response_set => @response_set})